apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: exam
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: exam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: meriem050/backend_image_monitor:1.0.0
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name:  db-config
                  key: mysql-server
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: mysql-database-name
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: username
         
